# Site settings
title: "On Software Engineering, Mathematics<br>and Philosophy"
author: "Nobody"
description: "This is a blog about software, start-up and life style."
keywords: "Software Engineering, Start-up, Philosophy"
colophon: "Content rights reserved. Themed with © MMXIII — MMXVI by Hugo Sereno Ferreira.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "https://dlp-inc.github.io/histories"

google-analytics:

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
